Repository filletournesols/DEV002-data-lovers, pull requests merged in 2022-11, with the labels that each got.

#1 Eliminacion de archivos que no van a utilizarse, cambio de nombre a r…
  README.md
  src/Datalovers.md
  src/data/athletes/README.md
  src/data/athletes/README.pt-BR.md
  src/data/athletes/athletes.js
  src/data/athletes/athletes.json
  src/data/ghibli/README.md
  src/data/ghibli/README.pt-BR.md
  src/data/ghibli/ghibli.js
  src/data/ghibli/ghibli.json
  src/data/harrypotter/README.md
  src/data/harrypotter/README.pt-BR.md
  src/data/harrypotter/data.js
  src/data/harrypotter/harry.json
  src/data/lol/README.md
  src/data/lol/README.pt-BR.md
  src/data/lol/lol.js
  src/data/lol/lol.json
  src/data/pokemon/README.md
  src/data/pokemon/README.pt-BR.md
  src/data/pokemon/pokemon.js
  src/data/pokemon/pokemon.json
  src/data/rickandmorty/README.md
  src/data/rickandmorty/README.pt-BR.md
  src/data/rickandmorty/rickandmorty.js
  src/data/rickandmorty/rickandmorty.json
  thumb.png
Labels: documentation

#2 Visualización personajes
  src/characters.html
  src/index.html
  src/result.html
Labels: documentation, enhancement

#10 Responsive de SPA
  src/assets/filter.png
  src/assets/filter.svg
  src/assets/sort.png
  src/assets/sort.svg
  src/index.html
  src/main.js
  src/style.css
Labels: documentation, enhancement

#12 Correcciones, estilos y responsive
  src/index.html
  src/style.css
Labels: bug, documentation, enhancement

#15 Json de personajes
  src/data_api/data.json
Labels: documentation

#16 Menú de ordenamiento
  src/index.html
  src/main.js
  src/style.css
  test/data.spec.js
Labels: bug, documentation, enhancement

#17 Añadiendo filter menu
  src/index.html
  src/main.js
  src/style.css
Labels: bug, documentation, enhancement

#19 Nueva carpeta de test para DOM y test de fetch en data con mock para fetch
  .eslintrc
  package-lock.json
  package.json
  src/data.js
  src/main.js
  src/style.css
  test/data.spec.js
  test/dom.spec.js
  test/main.spec.js
Labels: bug, enhancement

#20 Resolviendo bugs de merge
  src/index.html
  src/main.js
  src/style.css
Labels: bug

#21 Character card
  src/index.html
  src/main.js
  src/style.css
Labels: bug, documentation, enhancement

#22 función lupa más botón de status sin CSS
  package-lock.json
  package.json
  src/chartDeadOrAlive.js
  src/data.js
  src/index.html
  src/main.js
  src/style.css
  test/data.spec.js
  test/dom.spec.js
  test/main.spec.js
Labels: bug, documentation, enhancement, help wanted

#23 Creando test de fiilter
  test/data.spec.js
Labels: documentation, wontfix

#24 Modificacion de archivos
  README.md
  images/DA-desktop.png
  images/DA-mobile.png
  images/bajaFidelidad1.png
  images/bajaFidelidad2.png
  test/main.spec.js
Labels: documentation
